# 配置文件，在这里填写api

weatherXinZhi: Sxxxxxxx          #心知天气api   从https://www.seniverse.com/注册获取
sauceno-api: bxxxxxx             #sauceno搜图api，你可以从https://saucenao.com/user.php注册并获取
moderate: 1xxxxxx                #色图审核api 从https://www.moderatecontent.com/获取
siZhiAi:                         #思知ai，已不建议使用，建议用ai，如果你还是想用。从https://console.ownthink.com/login                      
  - 5298b4b366987f06ab07b9015bb6a5a2    # 第一个apiKey
  - 806948824e6e559ff64ba689901483be    # 第二个，所有多apikey都可以这样填写
nasa_api: HSxxxxxxx              #nasa相关天文api 从https://api.nasa.gov/index.html#main-content申请
chatGLM: 69xxxxxxx               #chatGLM的apiKey，从https://open.bigmodel.cn/获取
gemini:                          #谷歌的gemini api，免费的，有几个填几个，在https://ai.google.dev/tutorials/setup?hl=zh-cn获取，需要配置代理，否则无法使用
  - AIxxxxxxxx
cozi: https://xxxxxx.zeabur.app/v1/chat/completions  # https://github.com/avilliai/Manyana/issues/4
proxy: ''  #代理 http://127.0.0.1:端口 如http://127.0.0.1:10809 自己设置对应的端口，没有就不填，v2ray是7890，clash一般7890，ssr一般1080
openai-keys:                     #openai官方的apikey，或免费从https://github.com/chatanywhere/GPT_API_free?tab=readme-ov-file申请
  - sk-Mxxxxxxxxxxx
gpt3.5-dev: false                #如果是从https://github.com/chatanywhere/GPT_API_free?tab=readme-ov-file申请openai-apikey，请打开此开关，这样就无需代理即可使用
modelscopeCookie: ""            #modescopeTTS增加反爬虫，默认留空用我的，如不能用了自行抓取cookie，查看https://github.com/avilliai/Manyana/issues/7
bert_colab: "https://mess-addressed-openings-exposed.trycloudflare.com/synthesize"      #新版本Manyana无需配置此功能，语音合成选modelscopeTTS模式可直接使用。但如果你喜欢折腾：bert_vits_colab部署：https://colab.research.google.com/drive/1n8lI6pOiDtli2zC5fL9PZ9TZqbOafqma?usp=sharing 请注意，使用此功能必须配置上面的proxy项

