# 配置文件，在这里填写api

weatherXinZhi: SeSIadf8hL-BdFfdanhE9MKb #心知天气api   从https://www.seniverse.com/注册获取
youdao:
  app_id: 67edf72f62fda13cdf548       #有道翻译 https://ai.youdao.com/?keyfrom=fanyi-new-nav#/
  app_key: XzFaBbE9zGdVLtdafapCJHzADWIXhHvdnB0T
sauceno-api: b1f0saf18dbf8b7c21cdfdafz38b4d9ad0211f8db1c4eaf20 #sauceno搜图api，你可以从https://saucenao.com/user.php注册并获取
moderate: 207b10178c64089dvzv90ebfcd7f865d97a   #色图审核api 从https://www.moderatecontent.com/获取
poe-api:
  - BHai3yLdvOcjdadfzS6UnIX6A%3D%3D  #从poe.com抓取到token，可获取多个
siZhiAi: 819d9jyeb3da9b2b5cba26d2430a     #思知ai    从https://console.ownthink.com/login
nasa_api: dfafhalsdfalfdj              # nasa相关天文api 从https://api.nasa.gov/index.html#main-content申请
proxy: 'http://127.0.0.1:1080'  #代理 自己设置对应的端口，没有就不填

