# 配置文件，在这里填写api

weatherXinZhi: Sxxxxxxx    #心知天气api   从https://www.seniverse.com/注册获取
sauceno-api: bxxxxxx      #sauceno搜图api，你可以从https://saucenao.com/user.php注册并获取
moderate: 1xxxxxx           #色图审核api 从https://www.moderatecontent.com/获取
siZhiAi:                             #思知ai，不建议，建议chatGLM    从https://console.ownthink.com/login
  - 5298b4b366987f06ab07b9015bb6a5a2    # 第一个apiKey
  - 806948824e6e559ff64ba689901483be    # 第二个，你有几个就填几个，按照如下格式即可。多删少补
nasa_api: HSxxxxxxx            # nasa相关天文api 从https://api.nasa.gov/index.html#main-content申请
chatGLM: 69xxxxxxx        #chatGLM的apiKey，从https://open.bigmodel.cn/获取
gemini: AIxxxxxxxx       #谷歌的gemini api，免费的，在https://ai.google.dev/tutorials/setup?hl=zh-cn获取，需要配置代理，否则无法使用
cozi: https://xxxxxx.zeabur.app/v1/chat/completions  # https://github.com/avilliai/Manyana/issues/4
proxy: 'http://127.0.0.1:10809'  #代理 自己设置对应的端口，没有就不填
openai-keys:                 #openai官方的apikey，淘宝搜apikey，0.7块一个，有代理的话，settings.yaml中模型就写gpt3.5，没代理的之后更新
  - sk-Mxxxxxxxxxxx
bert_colab: "https://mess-addressed-openings-exposed.trycloudflare.com/synthesize"      #新版本Manyana无需配置此功能，语音合成选modelscopeTTS模式可直接使用。但如果你喜欢折腾：bert_vits_colab部署：https://colab.research.google.com/drive/1n8lI6pOiDtli2zC5fL9PZ9TZqbOafqma?usp=sharing 请注意，使用此功能必须配置上面的proxy项

