defaultModel:
  modelSelect:
  - voiceModel/nene/1374_epochsm.pth
  - voiceModel/nene/config.json
  speaker: 2
banGroups:
- 2132321
- 879886836
banUser:
- 1
- 4564949845
- 1840094972
superBlGroups:
  - 967444654
moderate:
  apiKeys:
    '699455559': fadfasfasf
  banTime: 300
  banWords:
    '60844343475':
    - 斯卡蒂
  groups:
    '69945555439': 1
  threshold: 40
trustGroups:
- 699455559
