#群聊小游戏设定
#轮盘赌
RouletteGame:
  bantime: 100 #禁言时间长度(秒)
  prohibited:        #你可以继续添加
    - 无法重复创建赌局
    - 本群已经开启了一个赌局
    - 杂鱼不能创建赌局哦❤
  muteWord:
    - 被禁言了吧，杂鱼❤
    - 杂鱼❤杂鱼❤
  unmute:
    - 杂鱼运气还不错嘛
    - 空枪，下一个
  muteFailed:        #在下面继续添加即可
    - bot权限不足，杂鱼❤可以再嚣张一会哦
    - 没有足够的权限