
wReply: # 自定义回复
  voiceRate: 20     #语音回复的概率
  replyRate: 5       #不艾特时的回复概率
  sizhi: False         #是否启用思知ai
  turnMessage: True   #是否启用私聊转发
  banWords: ['妈', '主人', '狗', '老公', '老婆', '爸', '奶', '爷', '党', '爹', 'b', '逼', '牛', '国', '批'] #词库违禁添加词汇
banGroups:            #黑名单群
  - 1235799
  - 578904
banUser:              #黑名单用户
  - 91793712344
  - 741927340