banGroups:
- 1235799
- 578904
banUser:
- 91793712344
- 741927340
moderate:
  banTime: 300
  banWords:
    '60844343475':
    - 斯卡蒂
  groups:
    '69945555439': 1
  threshold: 40
wReply:
  banWords:
  - 妈
  - 主人
  - 狗
  - 老公
  - 老婆
  - 爸
  - 奶
  - 爷
  - 党
  - 爹
  - b
  - 逼
  - 牛
  - 国
  - 批
  replyRate: 5
  sizhi: false
  turnMessage: true
  voiceRate: 20
