defaultModel:
  modelSelect:
  - voiceModel/nene/1374_epochsm.pth
  - voiceModel/nene/config.json
  speaker: 2
setu: false
wReply:
  banWords:
  - 妈
  - 主人
  - 狗
  - 老公
  - 老婆
  - 爸
  - 奶
  - 爷
  - 党
  - 爹
  - b
  - 逼
  - 牛
  - 国
  - 批
  chineseVoiceRate: 30
  replyRate: 3
  sizhi: false
  turnMessage: true
  voiceRate: 30
