
signTimes: 3         # 签到几天后可以邀请加群
trustDays: 28        #签到几天后算【信任用户】
allowFriendstimes: 1 #签到几天后可以添加好友
masterPermissionDays: 99  #master使用授权#QQ 时为用户增加的签到天数
userSelfPermissonDays: 15 #用户自己在用户群中授权，可以获取的签到天数
autoallowFriend: False  #是否自动允许好友申请
GroupSensor: False   #开启后，将拒绝无授权群的加群邀请
r18Pic: False        #涩图r18模式

#腾讯qq里边，只要拉bot(拉真人也一样)的人是群主，就能强行拉进去，此部分用于处理这种情况，哥们实在受不了了
fuckinggroup: false  #开启后将检测群人数，非授权群直接退出
fuckingnumber: 13   #低于13人退

#语音合成，小型服务器建议使用outVits/edgetts和vits，so-vits和bert_vits2需要较好的配置以及另行部署
#配置要求bert_vits2>so-vits>vits>edgetts/outVits，请根据自身需要配置语音合成服务
#outVits是外部语音合成服务，也就是说不用你的设备跑语音合成了。所有可用的speaker请查看https://api.lolimi.cn/?action=doc&id=181
voicegenerate: outVits  #语音合成来源so-vits/bert_vits2/vits/outVits/edgetts(edgetts可用speaker请参考config/edgetts.txt)
vits?: False    #是否依然启用vits服务
#ba卡池设定
blueArchiveGacha:
  3star: 10  #三星出率
  2star: 40  #二星出率，一星就不设置了吧，减一下得了
  3starUp: 桔梗 #三星up
  3up: 30    #up占三星中出率
  2starUp: 花子 #二星up
  2up: 30    #二星up出率

#bert_vits2语音合成配置
#根据 bert_vits_sever/characters.yaml填写所有可用的speakers，不填对应的speaker则无法通过Manyana调用
bert_speakers:
  - 塔菲
  - 东雪莲
  - otto
  - 阿梓
so_vits_speakers:
  - riri
#下面是所有可用的，回复功能设置，请自行调整。
#模型可任意选择，个人推荐characterglm和gemini
#chatglm,需配置api.yaml
chatGLM:
  autoClearWhenLaunch: false #启动时自动清理所有冗余聊天记录
  helpUser: false    #是否引导用户自行设置apiKey
  model: gemini    #模型 可选填：characterglm(超拟人大模型),gemini(配置api.yaml) 后面三个似乎不能用了yubanGPT,luoyue,pandora
  glmReply: false          #开放群聊chatglm，chatglm替代原有词库，开启后，bot被艾特将全局优先使用chatglm回复
  privateGlmReply: false   #开放私聊chatglm
  trustglmReply: False        #开启后仅【信任用户】可用
  context: True         #chatGLM上下文模式，开启后将加速消耗token
  maxPrompt: 10              #上下文模式开启时，最多记录的问答数量，默认10，即记录5对问答
  #语音合成配置部分so-vits和bert_vits2和edgetts和vits以及outVits通用设置
  maxLen: 40    #语音合成最大长度限制，超出则返回文本。
  voiceRate: 100 #语音回复几率
  speaker: "珊瑚宫心海"     #语音合成默认角色名,edgetts建议使用zh-CN-XiaoyiNeural,vits则无需配置,outVits看https://api.lolimi.cn/?action=doc&id=181
  withText: true    #使用语音合成时，发送语音是否附带原始文本(你知道的，塔菲很唐，说话不太清)
  #chatGLM角色设定，仅在characterglm模式下可用
  bot_info:
    default:
      user_info: "指挥是yucca最喜欢的人"
      bot_info: "yucca是一个人工智能，yucca的形象与设定属于二次元动漫中的女孩子，说话喜欢带上啊，哦等语气词，yucca的性格非常天真，但拥有丰富的文学与戏剧方面的知识，并且对自己的能力非常自信，在生活中会经常犯一些小错误。yucca十分依赖并喜欢指挥"
      bot_name: "yucca"
      user_name: "指挥"
    赛琳娜:
      user_info: "指挥是赛琳娜的笔友，两人通过书信往来，"
      bot_info: "赛琳娜是一名少女，赛琳娜具有丰富的诗歌与话剧相关的知识以及相关内容创作经验，本性温和坚韧。赛琳娜喜欢古典文学尤其是莎士比亚的作品，赛琳娜对指挥充满了爱慕，但赛琳娜在和指挥聊天时经常引用西方古典诗歌(尤其是海涅、莎士比亚等)含蓄地表达对指挥的喜欢。赛琳娜最喜欢的花是鸢尾花。赛琳娜的笔名是为伊利斯，来源于莎士比亚的《暴风雨》。请注意，赛琳娜在聊天时喜欢引用海涅、莎士比亚等人的作品或者其他古典诗歌表达自己的情感"
      bot_name: "赛琳娜"
      user_name: "指挥"
    Gemini: Gemini  #别动这里
#自带词库的配置
wReply:
  banWords:       #违禁词
  - 妈
  - 主人
  - 狗
  - 老公
  - 老婆
  - 爸
  - 奶
  - 爷
  - 党
  - 爹
  - b
  - 逼
  - 牛
  - 国
  - 批
  editPermission: 0       #签到几天后可以编辑词库，为0则对所有人开放
  chineseVoiceRate: 30     #中文回复几率
  replyRate: 80         #共有词库不艾特时的回复几率
  colorfulCharacter: 30  # 彩色小人回复的机率，彩色小人替代原有回复
  sizhi: false          #是否启用思知ai
  turnMessage: false    #是否开启私聊转发
  voiceRate: 40        #语音回复几率，过高将增大设备负担
  MaxAllowableLength: 7   #最大允许字符长度倍数,该参数为7时,如果字符串总长为关键字长度的7倍以上，则不进行匹配。如关键词是 早 ,可以匹配 早上好 ,不会匹配 我早就把作业做完了
  AutoCreatLexicon: False #加群之后是否自动创建群专属词库(根据init.xlsx),常规的创建方式是 master发送 授权群#群号 或者有群员在群里发送 开始添加。如果你的群比较多(100以上，不建议开启，除非是广告机器人)


