
signTimes: 3    # 签到几天后可以邀请加群
GroupSensor: False    #开启后，将拒绝无授权群的加群邀请
wReply:
  banWords:       #违禁词
  - 妈
  - 主人
  - 狗
  - 老公
  - 老婆
  - 爸
  - 奶
  - 爷
  - 党
  - 爹
  - b
  - 逼
  - 牛
  - 国
  - 批
  chineseVoiceRate: 30     #中文回复几率
  replyRate: 3         #共有词库不艾特时的回复几率
  groupLexicon: 50     #各群专有词库不艾特时的回复几率（调这个就行）
  sizhi: false          #是否启用思知ai
  turnMessage: true    #是否开启私聊转发
  voiceRate: 40        #语音回复几率，过高将增大设备负担

