
signTimes: 3    # 签到几天后可以邀请加群
GroupSensor: False    #开启后，将拒绝无授权群的加群邀请
r18Pic: False
wReply:
  banWords:       #违禁词
  - 妈
  - 主人
  - 狗
  - 老公
  - 老婆
  - 爸
  - 奶
  - 爷
  - 党
  - 爹
  - b
  - 逼
  - 牛
  - 国
  - 批
  chineseVoiceRate: 30     #中文回复几率
  replyRate: 3         #共有词库不艾特时的回复几率
  groupLexicon: 100    #各群专有词库不艾特时的回复几率（调这个就行）
  sizhi: false          #是否启用思知ai
  turnMessage: true    #是否开启私聊转发
  voiceRate: 40        #语音回复几率，过高将增大设备负担
  MaxAllowableLength: 7   #最大允许字符长度倍数,该参数为7时,如果字符串总长为关键字长度的7倍以上，则不进行匹配。如关键词是 早 ,可以匹配 早上好 ,不会匹配 我早就把作业做完了
  AutoCreatLexicon: False #加群之后是否自动创建群专属词库(根据init.xlsx),常规的创建方式是 master发送 授权群#群号 或者有群员在群里发送 开始添加。如果你的群比较多(100以上，不建议开启，除非是广告机器人)

